# secrets.toml
smtp_server = "smtp.gmail.com"
smtp_port = 587
email_user = "abcdf2024dfabc@gmail.com"
email_password = "hjdd gqaw vvpj hbsy"
notification_email = "polanco@unam.mx"
csv_convocatorias_file = "registro_convocatorias.csv"
remote_host = "187.217.52.137"
remote_user = "POLANCO6"
remote_password = "tt6plco6"
remote_port = 3792
remote_dir = "/home/POLANCO6"
remote_file = "registro_convocatorias.csv"
local_file = "registro_convocatorias.csv"
local_file_pdf = "convocatoria.pdf"
remote_file_csv = "registro_convocatorias.csv"
remote_file_pdf = "convocatoria.pdf"
local_file_csv = "registro_convocatorias.csv"
remote_file_cor = "registro_correccion.csv"
local_file_cor = "registro_correccion.csv"
