# .streamlit/secrets.toml (en GitHub)
smtp_server = ""
smtp_port = ""
email_user = ""
email_password = ""
notification_email = ""
remote_host = ""
remote_user = ""
remote_password = ""
remote_port = ""
remote_dir = ""
remote_file_cor = "registro_correccion.csv"
local_file_cor = "registro_correccion.csv"
remote_file_csv = "registro_convocatorias.csv"
local_file_csv = "registro_convocatorias.csv"
